version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "bref-runtime-versions-website"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-10aoieu2oxixo"
s3_prefix = "bref-runtime-versions-website"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
